### ISSUE TITLE
Build for windows - pthread.lib not found

### ISSUE THREAD

**Issue by andyoknen** [olegtarasov/fastText#3]
Hi. I'm not a C++ expert, so I'm having trouble compiling the library for Windows. Can you help me with this case? What should I do additionally to build the dll. I use CMake-GUI to generate an SLN file, and I also tried opening it in Visual Studio 2019 and building it there. In both cases, the build does not end successfully-swears about the lack of pthread

**Comment by olegtarasov** [comment]
Hi @andyoknen ! Sorry, it took me a long time to get to this issue. First of all, the easiest way to build this library under Windows is to use the latest CMake from command line (from CMakeLists.txt directory):

```
mkdir build
cd build
cmake -DCMAKE_GENERATOR_PLATFORM=x64 ..
cmake --build . --config Release --target fasttext-shared
```

Notice that we build only a DLL (`fasttext-shared` CMake target). You are probably trying to build an executable form of this library (`fasttext-bin` CMake target). It links to `pthread` for Linux, but there is no such library in Windows. You would need to verify it, but it seems that you can just modify line 74 in CMakeLists.txt:

```
target_link_libraries(fasttext-bin fasttext-static)
```

I didn't include additional cross-platform conditions in CMakeLists.txt, since I don't need an executable version of this code and I try to keep my modifications minimal for the ease of merging with upstream.
